### ISSUE TITLE
afterRender / childrenComplete

### ISSUE THREAD

**Issue by brianmhunt** [knockout/tko#47]
Analogous to the Knockout 3.5 line:

- [ ] knockout/knockout@5d3d60a Support afterRender for if, ifnot and with bindings, fixes #2099
- [ ] knockout/knockout@3d7cf10 Merge pull request #2310 from knockout/afterRender-generic
- [ ] knockout/knockout@ccc5653 Rename afterRender to childrenComplete. Make it work with template and foreach bindings. Add framework for addition binding events.
- [ ] knockout/knockout@785464f Add spec for component custom element
- [ ] knockout/knockout@b7decfd Make sure a null afterRender doesn't fail + add some tests
- [ ] knockout/knockout@bf48f00 expand afterRender tests
- [ ] knockout/knockout@4740bb3 afterRender binding works with any binding that calls ko.applyBindingsToDescendants or with just normal binding processing (more tests to come).
- [ ] knockout/knockout@0003397 afterRender should work when used with virtual element
- [ ] knockout/knockout@bc398f0 Merge branch '2099-improve-support-afterrender' of https://github.com/cervengoc/knockout

* [ ]  knockout/knockout@34b4123 - Merge pull request #2319 from knockout/1533-component-afterrender-generic (3 weeks ago) <Michael Best>
 * [ ] knockout/knockout@c64547c - Grammar and minor fixes (4 weeks ago) <Michael Best>
 * [ ] knockout/knockout@d913cf0 - rename component afterRender to koDescendantsComplete (4 weeks ago) <Michael Best>
 * [ ] knockout/knockout@1c80469 - Update logic for async completion ancestor linkage and disposal (4 weeks ago) <Michael Best>
 * [ ] knockout/knockout@01975ae - Expand binding event to handle descendant completion for components (5 weeks ago) <Michael Best>
 * [ ]  knockout/knockout@fc2ff32 - Merge branch 'master' into 1533-component-afterrender-trigger-option2 (6 weeks ago) <Michael Best>
 * [ ] knockout/knockout@d64df2e - (origin/1533-component-afterrender-trigger-option2) Update approach; always trigger afterRender after all subcomponents are complete (2 months ago) <Michael Best>
 * [ ]  knockout/knockout@20f2c69 - component afterRender: pass element, always synchronous if synchronous:true, update specs (1 year, 1 month ago) <Michael Best>
 * [ ] knockout/knockout@14d147a - Component afterRender that is triggered when all child components have rendered, no matter how long it takes. This is option 2 in https://github.com/knockout/knockout/issues/1533#issuecomment-261458567 (1 year, 1 month ago) <Michael Best>
* [ ] knockout/knockout@3d7cf10 - Merge pull request #2310 from knockout/afterRender-generic (6 weeks ago) <Michael Best>
