### ISSUE TITLE
🎥    Incorporate ongoing PRs from Knockout/knockout

### ISSUE THREAD

**Issue by brianmhunt** [knockout/tko#5]
From: 
```bash
$ git log "v3.4.0"..HEAD --oneline
```

# Complete

* [x] knockout/knockout@b5eff3e - (HEAD -> master, origin/master, origin/HEAD) fixes #1440: package.json now points to minified version (2 weeks ago) <Michael Best>
* [x]  knockout/knockout@8237b7f - Merge pull request #907 from knockout/907-no-child-context-with-as (2 weeks ago) <Michael Best>
 * [x] knockout/knockout@89b056e - Add noChildContextWithAs option to not create a child binding context when using the `as` option with `with` or `foreach`. (3 weeks ago) <Michael Best>
* [x] knockout/knockout@e4ecf89 - Fix white-space issue from earlier commit (3 weeks ago) <Michael Best>
* [x] knockout/knockout@9f7afe8 - Merge branch 'timtucker-patch-4' (3 weeks ago) <Michael Best>
 * [x] knockout/knockout@1689461 - Check for existance of array instead of reassigning (4 years, 1 month ago) <Tim Tucker>
* [x]   knockout/knockout@f33833e - Merge branch 'master' of github.com:knockout/knockout (3 weeks ago) <Michael Best>
 * [x]   knockout/knockout@b74da93 - Merge pull request #1077 from DodekaHydra/patch-1 (3 weeks ago) <Michael Best>
  * [x]  knockout/knockout@09638bd - QOL update for selectExtensions.js; cleanup nested switches (4 years, 4 months ago) <Andrew Spade>
* [x]   knockout/knockout@b984ccc - Merge branch 'pimterry-no-empty-templates' (3 weeks ago) <Michael Best>
 * [x] knockout/knockout@306e181 - Add test for empty anonymous foreach templates too (4 years, 1 month ago) <pimterry>
 * [x] knockout/knockout@8312dc7 - Detect and reject (probably accidentally) empty anonymous templates (4 years, 1 month ago) <pimterry>
* [x] knockout/knockout@7c2a339 - Allow a cleaned comment node to remove "children" fixes #1740 (3 weeks ago) <Michael Best>
 * [x] knockout/knockout@11182a3 - `as:` binding can be used with `with:` (9 weeks ago) <Michael Bøcker-Larsen>
- [x] knockout/knockout@cdd2741 Throw an error from ko.isObservable if it detects an observable from another Knockout instance. fixes #1344 ko.isObservable(ko.computed) now returns false. fixes #1958
- [x] knockout/knockout@cee294c Merge branch 'master' of https://github.com/rampion/knockout into rampion-master
- [x] knockout/knockout@2606678 fix setAttribute issue in Chrome (see #1066); fix using function as `with` argument (fixes #2285)
- [x] knockout/knockout@19d5022 Merge pull request #2296 from bennieswart/context_properties_no_minify
- [x] knockout/knockout@f5baa12 Hide or don't minify extra internal properties on binding context
- [x] knockout/knockout@4540c88 Add ko.when
- [x] knockout/knockout@3949c3e Simplify logic to check for dependency changes during awake
- [x] knockout/knockout@d7fc725 Merge branch 'master' of github.com:knockout/knockout
- [x] knockout/knockout@f916d57 Merge pull request #2279 from orbweaver-/2252-subscribable-toString
- [x] knockout/knockout@716eb28 fix textInput so that it won't update the model if the value is changed only by the browser. fixes #2281
- [x] knockout/knockout@195cdea Merge branch 'fix-side-effects-on-awake' of https://github.com/dancras/knockout
- [x] knockout/knockout@bd13741 Merge pull request #2301 from jsoref/spelling
- [x] knockout/knockout@822f147 Fix side effects on awake callback
- [x] knockout/knockout@07677ac Add toString function to subscribable
- [x] knockout/knockout@e57500a Merge pull request #2141 from knockout/2141-domdata-weakmap
- [x] knockout/knockout@c87ad68 Add comments about domData choices.
- [x] knockout/knockout@6c02fe1 Store data on the node itself (except in old IE), rather than using WeakMap.
- [x] knockout/knockout@199fdb2 Use WeakMap is available for domData storage.
- [x] knockout/knockout@b58e2b6 Merge pull request #2261 from knockout/2261-checked-binding-fix
- [x] knockout/knockout@fd4ed82 When bound to a checkbox, the "checkedValue" binding will affect a non-array "checked" binding, but "value" won't.
- [x] knockout/knockout@1b73f8a Merge pull request #2248 from OctaneLending/master
- [x] knockout/knockout@04a8f84 Merge pull request #2234 from knockout/2226-deferUpdates-if-binding-2
- [x] knockout/knockout@bb70d30 Don't expose inheritParentVm
- [x] knockout/knockout@01237e7 New specs to show proper behavior
- [x] knockout/knockout@5dc0ba0 Merge branch 'master' into 2226-deferUpdates-if-binding-2
- [x] knockout/knockout@fa17c59 deferred updates: only notify that a computed changed if it was evaluated
- [x] knockout/knockout@068a041 Added unit tests for #1482
- [x] knockout/knockout@d20958b Merge pull request #2240 from knockout/2240-deferred-computed-notify-update
- [x] knockout/knockout@554022b Make sure all descendant bindings of `if`, `with`, etc. have a dependency on the parent condition so that updates happen in the right order when using deferred updates.
- [x] knockout/knockout@86dfaf3 Accept bindings with comments (either C++ or C style) fixes #1524 and with backtick strings (template literals) fixes #2064
- [x] knockout/knockout@a32bd19 Add third parameter to ko.applyBindings for modifying the root context
- [x] knockout/knockout@5f10dfd Merge pull request #2227 from knockout/2227-computed-auto-dispose-fix
- [x] knockout/knockout@6268fc9 dispose a computed that depends only on inactive computeds
- [x] knockout/knockout@9798f6d export ko.utils.objectMap; fix test typo
- [x] knockout/knockout@187788a Fixes from recent merge "conflicts". Fix "sorted" so it works in old IE.
- [x] knockout/knockout@f9fe3d4 Merge pull request #2024 from knockout/2024-applyBindings-context-vars
- [x] knockout/knockout@975affd Merge pull request #2212 from far-blue/2072-expose-additional-methods
- [x] knockout/knockout@e3240c1 Merge pull request #1946 from WHenderson/master
- [x] knockout/knockout@62d5683 Implemented request for #1482
- [x] knockout/knockout@668636e Merge pull request #1448 from ismell/duck
- [x] knockout/knockout@61c039f In value binding, simplify model "rejection" handling (don't trigger a change event)
- [x] knockout/knockout@1592bdc Merge pull request #2226 from knockout/2226-deferUpdates-if-binding
- [x] knockout/knockout@992bc71 Should update "if" binding before descendant bindings
- [x] knockout/knockout@1997a5e Merge pull request #2221 from knockout/2221-hasFocus-writable
- [x] knockout/knockout@4391eb9 Merge pull request #2218 from knockout/2218-value-update-select
- [x] knockout/knockout@bd6e508 When updating the value of a `<select>` to null or "" when there's a caption, make sure the selection doesn't get reset to the original value. Also make the "workaround for IE 6" only run on IE6.
- [x] knockout/knockout@941a1f2 Merge pull request #2192 from knockout/2192-value-select-undefined
- [x] knockout/knockout@0a1581e Make sure you can select the caption when using valueAllowUnset and nothing is selected.
- [x] knockout/knockout@79d3f5f Merge branch 'hiddenbinding'
- [x] knockout/knockout@c29a923 Hidden binding
- [x] knockout/knockout@ccec0fc Merge pull request #2148 from knockout/2148-contextfor-undefined-for-unbound
- [x] knockout/knockout@65e7f0d Merge pull request #1899 from knockout/1899-new-checkValue-use
- [x] knockout/knockout@10ec231 Fix multiple anonymous template bindings with same nodes, based on code from @cervengoc
- [x] knockout/knockout@6897d17 Merge pull request #2215 from knockout/2215-array-sorted-remove-updates
- [x] knockout/knockout@0ee72ac Merge pull request #2217 from decden/2216-observable-array-leaks-last-value
- [x] knockout/knockout@99c1cd7 expose computedContext.registerDependency and ko_subscribable_fun.init as per issue #2072 to make it easier to write custom observables.
- [x] knockout/knockout@5f0b9a7 Add spec from 3.4.2
- [x] knockout/knockout@00b03e9 hasFocus (mixed case) also supports writing to vm properties
- [x] knockout/knockout@d57baad Merge pull request #2197 from knockout/2197-deferred-pure-computed-update
- [x] knockout/knockout@a73cee4 Further fix for #2174: don't re-evaluate on access after we know that no change occurred.
- [x] knockout/knockout@b70eebb Merge pull request #2170 from knockout/1201-named-template-performance
- [x] knockout/knockout@7c1f400 When using deferred updates, a sleeping pure computed should see pending changes to its dependencies
- [x] knockout/knockout@92f62a2 Merge pull request #1835 from knockout/1835-computed-intermediate-value-fix
- [x] knockout/knockout@e9cc711 When checking if an observable has a pending notification, also compare the value. If it hasn't actually changed, don't force the notification.
- [x] knockout/knockout@c2eaf27 If a computed reads an observable with a pending notification (possible intermediate value), ensure we get notified of the actual final value (bypass equality checks).
- [x] knockout/knockout@ac94715 Merge pull request #2163 from knockout/2163-deferred-shouldnt-notify-future-subs
- [x] knockout/knockout@19536d5 ko.contextFor and ko.dataFor return undefined for unbound elements even if they are descendants of a bound element.
- [x] knockout/knockout@1145f4d Merge pull request #2174 from knockout/2174-minimize-deferred-computed-eval
- [x] knockout/knockout@f5df3c2 Modify dirty/stale logic so that we don't need to check both isDirty and isStale
- [x] knockout/knockout@0b64dd8 When a notification is delayed, save a copy of subscriptions to only notify those present and not future subscriptions.
- [x] knockout/knockout@495a969 when using deferred updates, only evaluate a computed if one of its dependencies actually changes (rather than just being "dirty")
- [x] knockout/knockout@edd0823 fix test errors because of not supplying node to ko.applyBindings
- [x] knockout/knockout@87e8a59 Merge pull request #2171 from knockout/1735-spectate-event
- [x] knockout/knockout@4e55d4b Expand pureComputed spectate test to show why the version needs to be updated before the spectate event.
- [x] knockout/knockout@d781ab5 Fixes #1740: Don't clean nodes that are removed during the clean process. This fix works because the HTMLCollection returned by getElementsByTagName is live and will reflect nodes added or removed after it's run. It's not okay to add/remove nodes before the one being cleaned, so doing so will throw an exception.
- [x] knockout/knockout@4296eed observables notify a "spectate" event whenever their value changes. This is like the "change" event but is not delayed by rateLimit/deferred and will notify when a sleeping pure computed observable gets a new value (by being accessed). Subscribing to "spectate" will not awaken a sleeping pure computed either.
- [x] knockout/knockout@ac30244 fixes #1796 - in cross window situation, load template from same window in template/foreach
- [x] knockout/knockout@38b21b6 for test added for #1167, make it more robust by manually triggering blur event
- [x] knockout/knockout@766af4c Make value binding work with input[type=file] fixes #849
- [x] knockout/knockout@797e002 Added braces to if statement
- [x] knockout/knockout@072960f Added nullptr guard to avoid exceptions
- [x] knockout/knockout@89933a1 Fixed leaking when tracking array changes
- [x] knockout/knockout@05c7aa6 Add sorted and reversed methods to ko.observableArray. Throw error from remove if array item is moved/removed.
- [x] knockout/knockout@89617f7 PhantomJS 2.0 does not work with a relative path. Use file:/// See #1776
- [x] knockout/knockout@4e0a4c4 Improve performance of named templates by caching the parsed nodes so they can be used for future rendering by using cloneNode. This will only help if a template is used more than once, especially with `foreach`.
- [x] knockout/knockout@d2a9e44 throw error if ko.applyBinding called before DOM is loaded. fixes #1215
- [x] knockout/knockout@2f230dc Fixes #2151 Problem when valueAllowUnset is true and option value is 0 and model value is null
- [x] knockout/knockout@1523efb Use Object.prototype.hasOwnProperty.call instead of obj.hasOwnProperty. Fixes #888
- [x] knockout/knockout@11e3cb9 Add textInput autocomplete workaround for IE 10 and possibly others. Fixes #1167 Make textInput catch ESC changes in IE. Fixes #1678
- [x] knockout/knockout@241c26c Enhance fix for #1975 to only re-evaluate if the awakened dependency changes. Also add a lower-level test.
- [x] knockout/knockout@eb88065 Fix for #1975. Issue occurs when a computed is changed when awakening that dependent sleeping computed observables don't know that it was changed.
- [x] knockout/knockout@b3f24b1 Export computed._latestValue in debug mode (was removed in 2e0647e0f2).
- [x] knockout/knockout@d608c4c Merge pull request #1974 from ThomasMichon/array-subscriptions
- [x] knockout/knockout@756d06e Add new test for notifySubscribers cleanup
- [x] knockout/knockout@fd71d33 Clean up arrayChange notifySubscribers wrapper
- [x] knockout/knockout@e9e653e Merge pull request #1953 from knockout/1710-class-binding-part2
- [x] knockout/knockout@c02cf64 "class" binding only support class string. "css" binding continues to support object and string forms.
- [x] knockout/knockout@c3bb9a3 Change attribution in banner
- [x] knockout/knockout@6dbbbe2 Add bindingContext option to "export" dependencies. This means that the context won't track the dependencies, but they should be tracked by the calling code, which is responsible for re-creating the context. Use this option for "with" and "template".
- [x] knockout/knockout@2161ce0 Merge branch 'master' of https://github.com/yjo/knockout into 1415-with-rawdata
- [x] knockout/knockout@07ff098 Change checked binding to use checkedValue, if present, for checkboxes when not bound to an array.
- [x] knockout/knockout@10571c3 Re-organize checked binding specs to remove duplicate and excess code. Add some tests to verify important details when checkedValue is observable.
- [x] knockout/knockout@d57a392 Exporting getDependencies method
- [x] knockout/knockout@f4ff3af Adding method to retrieve ordered list of dependencies for computed observables
- [x] knockout/knockout@3d46cca Merge pull request #1710 from knockout/1710-class-binding
- [x] knockout/knockout@5f360aa Use jQuery if available for style binding. Otherwise, attempt the convert a-b format to aB, and add "px" to styles that expect it.
- [x] knockout/knockout@1fb6330 export ko.utils.cloneNodes
- [x] knockout/knockout@b98dd95 Fixes #1943: prevent circular deferred computeds from causing infinite loop by preventing recursive dirty notifications.
- [x] knockout/knockout@241a45c Merge remote-tracking branch 'origin/master'
- [x] knockout/knockout@0a35a80 Merge pull request #1811 from knockout/1811-using-binding
- [x] knockout/knockout@32bfa9d Fixed #2078: use jQuery's on if available instead of bind
- [x] knockout/knockout@b13ffb0 Clean up most external reference when disposing a computed. fixes #1405
- [x] knockout/knockout@3038ec6 Fixing code style inconsistency
- [x] knockout/knockout@9887559 Merge pull request #1792 from knockout/1792-let-binding
- [x] knockout/knockout@7785a44 When using contains, compare the parent if not an element. One of the "using" tests failed in PhantomJS because PhantomJS doesn't support "contains" for comments.
- [x] knockout/knockout@f07616a Add "using" binding (formerly called withlight).
- [x] knockout/knockout@509c9ef Add let binding
- [x] knockout/knockout@75abab1 Add class as an alias of css. This allows for combined static and dynamic class bindings.
- [x] knockout/knockout@281e195 Verify the view-model subscription count.
- [x] knockout/knockout@de2cac6 Update version to 3.5.0-pre
- [x] knockout/knockout@5bd6fa5 fix typo in test that made it not load in PhantomJS
- [x] knockout/knockout@6d5678f Allow direct reference to an observable view model within a rendered template using $rawData
- [x] knockout/knockout@d59a69a Allow direct reference to an observable view model within a 'with' binding using $rawData
- [x] knockout/knockout@227e417 Add spec for array change tracking value coercion
- [x] knockout/knockout@6544469 When it walks like a duck and quacks like a duck, it must be a duck.
- [x] knockout/knockout@55a9f87 Simplify errors for better browser compatibility
- [x] knockout/knockout@e69a5cb Throw errors if virtual tree traversal finds an unmatched ko closing comment
- [x] knockout/knockout@0b575f8 Implement support for namespaces in attr binding.
- [x] knockout/knockout@6d3d744 Add a spec to support namespaces in attr binding.
- [x] knockout/knockout@253d39c Merge pull request #2302 from knockout/231-improve-style-binding
- [x] knockout/knockout@7c61332 Merge pull request #1152 from pimterry/spot-extra-closing-comments
- [x] knockout/knockout@b670e94 Throw an error on any ko end comment that is a firstChild
- [x] knockout/knockout@37a6cde Add extra test for firstChild comment parsing
- [x] knockout/knockout@c051902 Ensure virtualElements.firstChild returns null for `<!-- ko text: abc --><!-- /ko -->`
- [x] knockout/knockout@0729145 fix spacing
- [x] knockout/knockout@5ee9e07 spelling: performance
- [x] knockout/knockout@25e33a9 spelling: update
- [x] knockout/knockout@53c851c spelling: successfully
- [x] knockout/knockout@0b42903 spelling: subscriptions
- [x] knockout/knockout@5489bdc spelling: reordered
- [x] knockout/knockout@4990641 spelling: pathological
- [x] knockout/knockout@2e6811a spelling: original
- [x] knockout/knockout@33f1935 spelling: notification
- [x] knockout/knockout@3f6c0d0 spelling: javascript
- [x] knockout/knockout@76570f6 spelling: falsy
- [x] knockout/knockout@23254a4 spelling: explicit
- [x] knockout/knockout@8c50861 spelling: dependent
- [x] knockout/knockout@13dfb82 spelling: dependencies
- [x] knockout/knockout@8bed828 spelling: dependent
- [x] knockout/knockout@7ee8377 spelling: asynchronously
- [x] knockout/knockout@12453af spelling: assistant
- [x] knockout/knockout@62721da spelling: accessor- [x] knockout/knockout@e41727d Merge pull request #2244 from PandelisZ/readme-readability
- [x] knockout/knockout@cacbf89 readme tripple space indentation
- [x] knockout/knockout@21175af Revert "Readme paragraph indentation"
- [x] knockout/knockout@4e0850d Readme paragraph indentation
- [x] knockout/knockout@1a83f67 Improved headings and snippet readability

**Comment by brianmhunt** [comment]
@mbest – I've noticed a bunch of changes to KO 3.4 since the tko fork (good work, btw); could you please add a link to each of the PRs/merges here, so we can track them and they can be incorporated without having to search through the KO issues database.  Otherwise I fear we may end up with some regressions from KO 3.4 to KO 4 (/TKO 1.).  Many thanks.

**Comment by JD-Robbs** [comment]
Like `git log "v3.4.0"..HEAD`? I.e. just a simple listing of commits (hash, author, data and description) since the `v3.4.0` tag.

**Comment by brianmhunt** [comment]
@mbest - Looks like `virtualElements` breaks some tests in TKO (that also indicate problems potentially with KO) if:

```javascript
  if (!node.nextSibling || isEndComment(node.nextSibling)) {
    return null
  }
```

is removed  from `firstChild`.

**Comment by brianmhunt** [comment]
@mbest - Thanks for all these PRs; I'll be caught up to the latest ones soon.

A couple notes I wanted to share:

1. Comments around new code have really helped; not just for their content, but especially because they generally provide unique searchable text that makes it easier to pare down where the changes are in the code-base.

2. I'm getting a bizarre error using the `with` binding, notably if you look at tko's `WithBindingHandler` in `with.js`, and the `WithBindingHandlerFailsInexplicably`, there's something amiss in that the latter fails the test `Should update "with" binding before descendant bindings` in `asyncBindingBehavior.js`.  However the topmost calls they make *appear* to be identical, and all other tests appear to pass.  I dug down and there seem to be a *lot* more calls to the `_evalIfChanged` with the version that works.  The essence of the problem occurring in the test appear to be that the observables are not being triggered in the correct order.

You can try it out by running `npm run watch` in the `tko.binding.if` directory, and compare them by renaming the export (i.e. changing `WithBindingHandlerFailsInexplicably` to `WithBindingHandler` and renaming the other so there's no name conflict).

I'll keep staring at it, but since it *seems* to be deep in the `deferUpdate` code I thought you might have some insight.

**Comment by brianmhunt** [comment]
Supplemental from `git log ccc5653..HEAD`

b5eff3e - (HEAD -> master, origin/master, origin/HEAD) fixes #1440: package.json now points to minified version (2 weeks ago) <Michael Best>
8237b7f - Merge pull request #907 from knockout/907-no-child-context-with-as (2 weeks ago) <Michael Best>
e4ecf89 - Fix white-space issue from earlier commit (3 weeks ago) <Michael Best>
9f7afe8 - Merge branch 'timtucker-patch-4' (3 weeks ago) <Michael Best>
f33833e - Merge branch 'master' of github.com:knockout/knockout (3 weeks ago) <Michael Best>
b984ccc - Merge branch 'pimterry-no-empty-templates' (3 weeks ago) <Michael Best>
b74da93 - Merge pull request #1077 from DodekaHydra/patch-1 (3 weeks ago) <Michael Best>
7c2a339 - Allow a cleaned comment node to remove "children" fixes #1740 (3 weeks ago) <Michael Best>
89b056e - Add noChildContextWithAs option to not create a child binding context when using the `as` option with `with` or `foreach`. (3 weeks ago) <Michael Best>
34b4123 - Merge pull request #2319 from knockout/1533-component-afterrender-generic (3 weeks ago) <Michael Best>
57d1fdd - Merge branch 'master' of https://github.com/mblarsen/knockout (4 weeks ago) <Michael Best>
c64547c - Grammar and minor fixes (4 weeks ago) <Michael Best>
d913cf0 - rename component afterRender to koDescendantsComplete (4 weeks ago) <Michael Best>
1c80469 - Update logic for async completion ancestor linkage and disposal (4 weeks ago) <Michael Best>
01975ae - Expand binding event to handle descendant completion for components (5 weeks ago) <Michael Best>
fc2ff32 - Merge branch 'master' into 1533-component-afterrender-trigger-option2 (6 weeks ago) <Michael Best>
3d7cf10 - Merge pull request #2310 from knockout/afterRender-generic (6 weeks ago) <Michael Best>
11182a3 - `as:` binding can be used with `with:` (9 weeks ago) <Michael Bøcker-Larsen>
d64df2e - (origin/1533-component-afterrender-trigger-option2) Update approach; always trigger afterRender after all subcomponents are complete (2 months ago) <Michael Best>
20f2c69 - component afterRender: pass element, always synchronous if synchronous:true, update specs (1 year, 1 month ago) <Michael Best>
14d147a - Component afterRender that is triggered when all child components have rendered, no matter how long it takes. This is option 2 in https://github.com/knockout/knockout/issues/1533#issuecomment-261458567 (1 year, 1 month ago) <Michael Best>
306e181 - Add test for empty anonymous foreach templates too (4 years, 1 month ago) <pimterry>
8312dc7 - Detect and reject (probably accidentally) empty anonymous templates (4 years, 1 month ago) <pimterry>
1689461 - Check for existance of array instead of reassigning (4 years, 1 month ago) <Tim Tucker>
09638bd - QOL update for selectExtensions.js; cleanup nested switches (4 years, 4 months ago) <Andrew Spade>
